ktor:
  application:
    modules:
      - io.github.mfabisiak.wdai.ApplicationKt.module
  deployment:
    port: 8082
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
